cars = {'Audi'           : ['A3','A3 CABRIOLET','A4','A6','A8 L','Q3','Q5','Q7','R8','RS5','RS6','RS7 SPORT BACK','S6','TT'],
        'BMW'            : ['1 SERIES','3 SERIES','3 SERIES GT','5 SERIES','6 SERIES','7 SERIES','BMW M3','BMW M4','BMW M5','BMW M6','BMW i8','X1','X3','X5','X6','Z4'],
        'Chevrolet'      : ['BEAT','CAPTIVA','CRUZE','ENJOY','SAIL','SAIL HATCH BACK','SPARK','TAVERA'],
        'Datsun'         : ['GO ','GO PLUS'],
        'Fiat'           : ['AVVENTURA','LINEA','LINEA CLASSIC','500- ABBARTH','PUNTO'],
        'Force'          : ['FORCE ONE','GURKHA'],
        'Ford'           : ['CLASSIC','ECO SPORTS','ENDEAVOUR','FIESTA ','FIGO','FIGO ASPIRE','FUSION','IKON'],
        'Honda'          : [],
        'Hyundai'        : [],
        'ICML'           : [],
        'ISUZU'          : [],
        'Jaguar'         : [],
        'Land Rover'     : [],
        'Mahindra'       : [],
        'Maruthi Suzuki' : [],
        'Mercedes Benz'  : [],
        'Mini'           : [],
        'Mitsubishi'     : [],
        'Nissan'         : [],
        'Porsche'        : [],
        'Renault'        : [],
        'Skoda'          : [],
        'Ssangyong'      : [],
        'Tata'           : [],
        'Toyota'         : [],
        'Volkswagen'     : [],
        'Volvo'          : []
}
