# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCode',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=70)),
                ('Aggregate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('vehicle_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledServiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceIdentifier', models.CharField(max_length=100)),
                ('ServiceInfo', models.CharField(max_length=1000)),
                ('Parts', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=500)),
                ('FuelType', models.CharField(max_length=20)),
                ('MinKM', models.IntegerField()),
                ('MaxKM', models.IntegerField()),
                ('ServiceIdentifier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCenterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('ContactNumber', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=200)),
                ('BuildingNo', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=200)),
                ('Town', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Pincode', models.CharField(max_length=20)),
                ('OwnerName', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=1000)),
                ('Images', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedCarBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
            ],
        ),
    ]
