# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('mobile', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=254)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', django_mysql.models.JSONField(default=dict)),
                ('vehicles', django_mysql.models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OTPTransactionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=200)),
                ('TranID', models.CharField(max_length=50)),
                ('OTPValue', models.CharField(max_length=20)),
                ('DateTime', models.CharField(max_length=50)),
                ('VerificationStatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_model_id', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('vehicle_registration_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('chassis_number', models.CharField(max_length=200)),
                ('customer_id', models.CharField(max_length=20)),
                ('total_kms', models.IntegerField()),
            ],
        ),
    ]
