# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
