# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20170811_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
