# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20170811_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verified_at',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
