# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 17:11
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_verified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='verified_at',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
