# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 19:42
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20170813_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vehicles',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
