# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyServiceBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('customer_address_id', models.CharField(default=None, max_length=20)),
                ('customer_latlon', models.CharField(default=None, max_length=100)),
                ('service_details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cservicebooking',
            name='feedback_stars',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='cservicebooking',
            name='feedback_text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='cservicebooking',
            name='service_details',
            field=models.TextField(),
        ),
    ]
