# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cservicebooking',
            name='booking_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emergencyservicebooking',
            name='booking_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
