# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0002_auto_20170817_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cservicebooking',
            name='feedback_stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cservicebooking',
            name='feedback_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='emergencyservicebooking',
            name='customer_address_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyservicebooking',
            name='customer_latlon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
