# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0003_auto_20170917_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cservicebooking',
            name='vehicle_model_id',
            field=models.CharField(max_length=50),
        ),
    ]
