# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0003_auto_20170817_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyservicebooking',
            name='feedback_stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emergencyservicebooking',
            name='feedback_text',
            field=models.TextField(null=True),
        ),
    ]
