# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0004_auto_20170919_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cservicebooking',
            name='job_card_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyservicebooking',
            name='job_card_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
